'use strict';

/**
 * GENERATED FILE -- DO NOT EDIT BY HAND.
 *
 * Regenerate with:  node tools/packet_contract.js --write
 *
 * The action names below are derived from the server source by scanning for
 * `{ action: '...' }` (outbound) and `data.action === '...'` (inbound).
 * tests/unit/packet_contract.test.js fails if this file drifts from the code,
 * which is exactly what happened when the list was maintained by hand: it
 * listed actions the server never handled and missed every feature added since.
 *
 * Generated: 67 inbound, 77 outbound.
 */

const PACKET = {
    // Client -> Server. The server dispatches on data.action.
    C2S: {
        ACCEPT_QUEST: 'accept_quest',
        ATTACK: 'attack',
        ATTACK_BOSS: 'attack_boss',
        AUCTION_BUY: 'auction_buy',
        AUCTION_LIST: 'auction_list',
        AUCTION_REQUEST: 'auction_request',
        AUTH_LOGIN: 'auth_login',
        AUTH_LOGOUT: 'auth_logout',
        AUTH_REGISTER: 'auth_register',
        BANK_DEPOSIT_GOLD: 'bank_deposit_gold',
        BANK_DEPOSIT_ITEM: 'bank_deposit_item',
        BANK_WITHDRAW_GOLD: 'bank_withdraw_gold',
        BANK_WITHDRAW_ITEM: 'bank_withdraw_item',
        BUY_ITEM: 'buy_item',
        CAST_HEAL: 'cast_heal',
        CAST_PURIFY: 'cast_purify',
        CAST_SPELL: 'cast_spell',
        CHAT: 'chat',
        CRAFT_ITEM: 'craft_item',
        DIALOGUE_CHOICE: 'dialogue_choice',
        DROP_ITEM: 'drop_item',
        EMOTE: 'emote',
        EQUIP_ITEM: 'equip_item',
        EVOLVE: 'evolve',
        FISH: 'fish',
        FRIEND_ADD: 'friend_add',
        FRIEND_LIST_REQUEST: 'friend_list_request',
        FRIEND_REMOVE: 'friend_remove',
        GUILD_BANK_DEPOSIT: 'guild_bank_deposit',
        GUILD_BANK_WITHDRAW: 'guild_bank_withdraw',
        INSPECT_PLAYER: 'inspect_player',
        INTERACT_CORPSE: 'interact_corpse',
        LEADERBOARD_REQUEST: 'leaderboard_request',
        LOGIN: 'login',
        MOVE: 'move',
        OPEN_CRAFTING: 'open_crafting',
        PARTY_ACCEPT: 'party_accept',
        PARTY_CREATE: 'party_create',
        PARTY_DECLINE: 'party_decline',
        PARTY_INVITE: 'party_invite',
        PARTY_LEAVE: 'party_leave',
        PICKUP_ITEM: 'pickup_item',
        SELECT_SUBCLASS: 'select_subclass',
        SELL_ITEM: 'sell_item',
        TALK_NPC: 'talk_npc',
        TEST_GRANT_GOLD: 'test_grant_gold',
        TEST_GRANT_ITEM: 'test_grant_item',
        TEST_GRANT_MANA: 'test_grant_mana',
        TEST_GRANT_XP: 'test_grant_xp',
        TEST_HEAL: 'test_heal',
        TEST_SPAWN_BOSS: 'test_spawn_boss',
        TEST_SPAWN_MOB: 'test_spawn_mob',
        TOGGLE_BLOCK: 'toggle_block',
        TOGGLE_MOUNT: 'toggle_mount',
        TRADE_ACCEPT: 'trade_accept',
        TRADE_ADD_ITEM: 'trade_add_item',
        TRADE_CANCEL: 'trade_cancel',
        TRADE_CONFIRM: 'trade_confirm',
        TRADE_DECLINE: 'trade_decline',
        TRADE_LOCK: 'trade_lock',
        TRADE_OFFER: 'trade_offer',
        TRADE_REMOVE_ITEM: 'trade_remove_item',
        TRADE_REQUEST: 'trade_request',
        TRADE_SET_GOLD: 'trade_set_gold',
        TRIGGER_BOSS_AOE: 'trigger_boss_aoe',
        UNEQUIP_ITEM: 'unequip_item',
        USE_ITEM: 'use_item'
    },

    // Server -> Client. The client dispatches on data.action.
    S2C: {
        AOE_IMPACT: 'aoe_impact',
        AOE_WARNING: 'aoe_warning',
        AUCTION_MAILBOX: 'auction_mailbox',
        AUCTION_SYNC: 'auction_sync',
        AUTH_ERROR: 'auth_error',
        AUTH_LOGOUT_SUCCESS: 'auth_logout_success',
        AUTH_REQUIRED: 'auth_required',
        AUTH_SUCCESS: 'auth_success',
        BANK_OPEN: 'bank_open',
        BANK_UPDATE: 'bank_update',
        BLOCK_CHANGED: 'block_changed',
        BOSS_AOE: 'boss_aoe',
        BOSS_SPAWNED: 'boss_spawned',
        CHAT: 'chat',
        CHEST_UPDATE: 'chest_update',
        COMBO: 'combo',
        CORPSE_REMOVE: 'corpse_remove',
        CORPSE_SPAWN: 'corpse_spawn',
        CRAFTING_OPEN: 'crafting_open',
        CRAFTING_SYNC: 'crafting_sync',
        DAMAGE: 'damage',
        EVOLUTION_COMPLETE: 'evolution_complete',
        FCT: 'fct',
        FISHING_RESULT: 'fishing_result',
        FORCE_POSITION: 'force_position',
        FRIENDS_LIST: 'friends_list',
        GROUND_SYNC: 'ground_sync',
        GUILD_INVITED: 'guild_invited',
        GUILD_SYNC: 'guild_sync',
        INSPECT_PLAYER_RESULT: 'inspect_player_result',
        INVENTORY_SYNC: 'inventory_sync',
        INVENTORY_UPDATE: 'inventory_update',
        ITEM_DICT: 'item_dict',
        LEADERBOARD_RESULT: 'leaderboard_result',
        LOG: 'log',
        LOGIN_ERROR: 'login_error',
        LOGIN_FAIL: 'login_fail',
        LOOT_RARE: 'loot_rare',
        MAP_DATA: 'map_data',
        MOB_FORGET: 'mob_forget',
        MOB_MOVE: 'mob_move',
        MOB_UPDATE: 'mob_update',
        MOUNT_CHANGED: 'mount_changed',
        NODE_REMOVE: 'node_remove',
        NODE_SYNC: 'node_sync',
        NPC_DIALOGUE: 'npc_dialogue',
        NPC_DIALOGUE_CLOSE: 'npc_dialogue_close',
        NPC_SYNC: 'npc_sync',
        OPEN_SHOP: 'open_shop',
        PARTY_INVITE: 'party_invite',
        PARTY_INVITED: 'party_invited',
        PARTY_SYNC: 'party_sync',
        PARTY_UPDATE: 'party_update',
        PHASE_CHANGE: 'phase_change',
        PLAYER_LEFT: 'player_left',
        PLAYER_UPDATE: 'player_update',
        PLAYERS_SYNC: 'players_sync',
        QUEST_JOURNAL: 'quest_journal',
        RATE_LIMITED: 'rate_limited',
        SERVER_SHUTDOWN: 'server_shutdown',
        SHOP_SYNC: 'shop_sync',
        SHOW_CLASS_SELECT: 'show_class_select',
        SHOW_SUBCLASS_SELECT: 'show_subclass_select',
        SKILL_UPDATE: 'skill_update',
        SPELL: 'spell',
        SPELL_ANIM: 'spell_anim',
        SPELL_COOLDOWN: 'spell_cooldown',
        STAMINA: 'stamina',
        STATUS: 'status',
        TIME_SYNC: 'time_sync',
        TRADE_CLOSE: 'trade_close',
        TRADE_COMPLETE: 'trade_complete',
        TRADE_LOCKED: 'trade_locked',
        TRADE_OPEN: 'trade_open',
        TRADE_REQUESTED: 'trade_requested',
        TRADE_UPDATE: 'trade_update',
        YOUR_ID: 'your_id'
    }
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = PACKET;
} else {
    window.PACKET = PACKET;
}
